migrate to target dev/1.0.0, remove unwraps
eclipse-zenoh/zenoh-backend-rocksdb pull request #106
Opened 2024-06-12 13:41 UTC by Charles-Schleich

Migrated to target dev/1.0.0
Minor bump to deps: `uhlc`, `serde_json`
improved error messages and logic when handling Options of Database handle and Column Family handles

2024-06-14 15:42 UTC, Mallets commented on Cargo.toml
> +zenoh-buffers = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "dev/1.0.0" }
In `dev/1.0.0` you should not be forced to import anything else than `zenoh` crate. Could you try to remove all crates excepts for `zenoh_backend_traits` and `zenoh-plugin-trait`?

2024-06-14 15:47 UTC, Mallets commented on src/lib.rs
> +        ZBuf::from(value.payload()).contiguous(),
Use of `ZBuf` is discouraged. If you just want to get a `Cow<[u8]>` out of *payload* you can do `value.payload().into::<Cow<[u8]>>()` which should be more explicit.

2024-06-17 15:13 UTC, Mallets commented on src/lib.rs
> +        value.payload().into::<Vec<u8>>(),
```suggestion
        value.payload().into::<Cow<[u8]>>(),
```

2024-06-17 15:16 UTC, milyin commented on src/lib.rs
> +            match std::num::NonZeroU128::new(1u128)
Looks too complex, but ok. Normally this should be the `zid` from current zenoh session, but this is addintional work to pass it

2024-06-17 15:18 UTC, milyin requested changes

2024-06-17 15:18 UTC, milyin commented on src/lib.rs
> +        (None, Some(_)) => bail!("Option for ColumFamily and {CF_DATA_INFO} were both 'None'"),
Why "both None" while only one of them is None?

2024-06-17 15:22 UTC, Charles-Schleich commented on src/lib.rs
> +            match std::num::NonZeroU128::new(1u128)
The previous function `new_reception_timestamp()` was doing this with a hardcoded value of `1` 
So i tried to make it match the old behaviour. I agree its too complex, how can we make this simpler ?

2024-06-17 15:24 UTC, Charles-Schleich commented on src/lib.rs
> +        (None, Some(_)) => bail!("Option for ColumFamily and {CF_DATA_INFO} were both 'None'"),
Yupp, that is on me. 
Fixing and pushing.

2024-06-17 15:31 UTC, Charles-Schleich commented on src/lib.rs
> +        value.payload().into::<Vec<u8>>(),
Implemented

2024-06-17 15:37 UTC, Mallets commented on src/lib.rs
> +            match std::num::NonZeroU128::new(1u128)
I think it's an antipattern passing by ` NonZeroU128` to create a timestamp. You should use https://github.com/eclipse-zenoh/zenoh/blob/2fccc37bb2dbe38558d58072be63dfe01ed350bd/zenoh/src/api/time.rs#L20 and passing the `session` as parameter.

2024-06-17 15:39 UTC, Mallets commented on src/lib.rs
> +        .write(&mut writer, encoding.to_string().as_bytes())
You can convert the `Encoding` to `EncodingProto` to support automatic serialization. You can do the opposite for deserialization.

2024-06-17 15:39 UTC, milyin commented on src/lib.rs
> +            match std::num::NonZeroU128::new(1u128)
Let's keep it as is for now

2024-06-17 16:07 UTC, Charles-Schleich commented on src/lib.rs
> +        .write(&mut writer, encoding.to_string().as_bytes())
Where is `EncodingProto` ?
I can't find a Struct or trait by that name in our codebase.

2024-06-17 16:09 UTC, Mallets commented on src/lib.rs
> +        .write(&mut writer, encoding.to_string().as_bytes())
Actually, https://github.com/eclipse-zenoh/zenoh/pull/1158 could be leveraged

2024-06-17 18:13 UTC, Charles-Schleich commented on src/lib.rs
> +        .write(&mut writer, encoding.to_string().as_bytes())
Bump review.

2024-06-18 08:32 UTC, milyin requested changes

2024-06-18 08:32 UTC, milyin commented on src/lib.rs
>      let codec = Zenoh080::new();
This is also the place to leverage new API without resorting to internal part. The `ZBytes` exposes the writer, it should not be necessary to access internal `Zenoh080`. Maybe we are lack of examples how to use the serializing API now. So this is also good place to make things right and have it as one of such examples

2024-06-18 08:32 UTC, milyin commented on src/lib.rs
>      let codec = Zenoh080::new();
This is also the place to leverage new API without resorting to internal part. As @Mallets told me, the `ZBytes` exposes the writer, it should not be necessary to access internal `Zenoh080`. Maybe we are lack of examples how to use the serializing API now. So this is also good place to make things right and have it as one of such examples.

Though it's also may be good idea to merge it as is and make right serialize/deserialize implementation in separate PR.
@Mallets , your opinion?

2024-06-18 09:49 UTC, Mallets approved these changes

2024-06-18 09:49 UTC, merged